//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoMDSD
    {
        public string MaBaoCaoMDSD { get; set; }
        public string Thang { get; set; }
        public Nullable<int> Xoa { get; set; }
        public string Nam { get; set; }
    }
}
