//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaoCaoDoanhThu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaoCaoDoanhThu()
        {
            this.CT_BaoCaoDT = new HashSet<CT_BaoCaoDT>();
        }
    
        public string MaBaoCaoDT { get; set; }
        public string Thang { get; set; }
        public double TongDoanhThu { get; set; }
        public Nullable<int> Xoa { get; set; }
        public string Nam { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_BaoCaoDT> CT_BaoCaoDT { get; set; }
    }
}
