//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_BaoCaoDT
    {
        public string MaCTBaoCaoDT { get; set; }
        public string MaBaoCaoDT { get; set; }
        public string MaLoaiPhong { get; set; }
        public double DoanhThu { get; set; }
        public string TyLe { get; set; }
    
        public virtual BaoCaoDoanhThu BaoCaoDoanhThu { get; set; }
        public virtual LoaiPhong LoaiPhong { get; set; }
    }
}
