//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_BaoCaoMDSD
    {
        public string MaCTBaoCaoMDSD { get; set; }
        public string MaBaoCaoMDSD { get; set; }
        public string MaPhong { get; set; }
        public int SoNgayThue { get; set; }
        public string TyLe { get; set; }
    }
}
