//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_HoaDon
    {
        public string MaCTHoaDon { get; set; }
        public string MaHoaDon { get; set; }
        public string MaPhieuThuePhong { get; set; }
        public int SoNgayThue { get; set; }
        public double ThanhTien { get; set; }
        public double TriGia { get; set; }
    
        public virtual HoaDonTT HoaDonTT { get; set; }
        public virtual PhieuThuePhong PhieuThuePhong { get; set; }
    }
}
