//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class CT_PhieuThuePhong
    {
        public string MaCTPhieuThuePhong { get; set; }
        public string MaPhieuThuePhong { get; set; }
        public string MaKhachHang { get; set; }
    }
}
