//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDonTT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDonTT()
        {
            this.CT_HoaDon = new HashSet<CT_HoaDon>();
        }
    
        public string MaHoaDon { get; set; }
        public string NguoiThanhToan { get; set; }
        public string DiaChiNguoiThanhToan { get; set; }
        public System.DateTime NgayThanhToan { get; set; }
        public double TriGia { get; set; }
        public Nullable<int> Xoa { get; set; }
        public string Thang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CT_HoaDon> CT_HoaDon { get; set; }
    }
}
