//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKhachSan
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLKHACHSANEntities : DbContext
    {
        public QLKHACHSANEntities()
            : base("name=QLKHACHSANEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BaoCaoDoanhThu> BaoCaoDoanhThus { get; set; }
        public virtual DbSet<BaoCaoMDSD> BaoCaoMDSDs { get; set; }
        public virtual DbSet<CT_BaoCaoDT> CT_BaoCaoDT { get; set; }
        public virtual DbSet<CT_BaoCaoMDSD> CT_BaoCaoMDSD { get; set; }
        public virtual DbSet<CT_HoaDon> CT_HoaDon { get; set; }
        public virtual DbSet<CT_PhieuThuePhong> CT_PhieuThuePhong { get; set; }
        public virtual DbSet<DanhMucPhong> DanhMucPhongs { get; set; }
        public virtual DbSet<HoaDonTT> HoaDonTTs { get; set; }
        public virtual DbSet<KhachHang> KhachHangs { get; set; }
        public virtual DbSet<LoaiKhachHang> LoaiKhachHangs { get; set; }
        public virtual DbSet<LoaiPhong> LoaiPhongs { get; set; }
        public virtual DbSet<PhieuThuePhong> PhieuThuePhongs { get; set; }
        public virtual DbSet<Phong> Phongs { get; set; }
    }
}
